// @generated by scripts/gen_event_enum.py — do not edit by hand.
// Source: tests/fixtures/events.json
//
// Public event count: 88

use serde::{Deserialize, Serialize};

/// All public `V2Event` type discriminators.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "catalog.updated")]
    CatalogUpdated,
    #[serde(rename = "command.executed")]
    CommandExecuted,
    #[serde(rename = "file.edited")]
    FileEdited,
    #[serde(rename = "file.watcher.updated")]
    FileWatcherUpdated,
    #[serde(rename = "global.disposed")]
    GlobalDisposed,
    #[serde(rename = "installation.update-available")]
    InstallationUpdateAvailable,
    #[serde(rename = "installation.updated")]
    InstallationUpdated,
    #[serde(rename = "integration.connection.updated")]
    IntegrationConnectionUpdated,
    #[serde(rename = "integration.updated")]
    IntegrationUpdated,
    #[serde(rename = "lsp.updated")]
    LspUpdated,
    #[serde(rename = "mcp.browser.open.failed")]
    McpBrowserOpenFailed,
    #[serde(rename = "mcp.tools.changed")]
    McpToolsChanged,
    #[serde(rename = "message.part.delta")]
    MessagePartDelta,
    #[serde(rename = "message.part.removed")]
    MessagePartRemoved,
    #[serde(rename = "message.part.updated")]
    MessagePartUpdated,
    #[serde(rename = "message.removed")]
    MessageRemoved,
    #[serde(rename = "message.updated")]
    MessageUpdated,
    #[serde(rename = "models-dev.refreshed")]
    ModelsDevRefreshed,
    #[serde(rename = "permission.asked")]
    PermissionAsked,
    #[serde(rename = "permission.replied")]
    PermissionReplied,
    #[serde(rename = "permission.v2.asked")]
    PermissionV2Asked,
    #[serde(rename = "permission.v2.replied")]
    PermissionV2Replied,
    #[serde(rename = "plugin.added")]
    PluginAdded,
    #[serde(rename = "project.directories.updated")]
    ProjectDirectoriesUpdated,
    #[serde(rename = "project.updated")]
    ProjectUpdated,
    #[serde(rename = "pty.created")]
    PtyCreated,
    #[serde(rename = "pty.deleted")]
    PtyDeleted,
    #[serde(rename = "pty.exited")]
    PtyExited,
    #[serde(rename = "pty.updated")]
    PtyUpdated,
    #[serde(rename = "question.asked")]
    QuestionAsked,
    #[serde(rename = "question.rejected")]
    QuestionRejected,
    #[serde(rename = "question.replied")]
    QuestionReplied,
    #[serde(rename = "question.v2.asked")]
    QuestionV2Asked,
    #[serde(rename = "question.v2.rejected")]
    QuestionV2Rejected,
    #[serde(rename = "question.v2.replied")]
    QuestionV2Replied,
    #[serde(rename = "reference.updated")]
    ReferenceUpdated,
    #[serde(rename = "server.connected")]
    ServerConnected,
    #[serde(rename = "session.compacted")]
    SessionCompacted,
    #[serde(rename = "session.created")]
    SessionCreated,
    #[serde(rename = "session.deleted")]
    SessionDeleted,
    #[serde(rename = "session.diff")]
    SessionDiff,
    #[serde(rename = "session.error")]
    SessionError,
    #[serde(rename = "session.idle")]
    SessionIdle,
    #[serde(rename = "session.next.agent.switched")]
    SessionNextAgentSwitched,
    #[serde(rename = "session.next.compaction.delta")]
    SessionNextCompactionDelta,
    #[serde(rename = "session.next.compaction.ended")]
    SessionNextCompactionEnded,
    #[serde(rename = "session.next.compaction.started")]
    SessionNextCompactionStarted,
    #[serde(rename = "session.next.context.updated")]
    SessionNextContextUpdated,
    #[serde(rename = "session.next.model.switched")]
    SessionNextModelSwitched,
    #[serde(rename = "session.next.moved")]
    SessionNextMoved,
    #[serde(rename = "session.next.prompt.admitted")]
    SessionNextPromptAdmitted,
    #[serde(rename = "session.next.prompted")]
    SessionNextPrompted,
    #[serde(rename = "session.next.reasoning.delta")]
    SessionNextReasoningDelta,
    #[serde(rename = "session.next.reasoning.ended")]
    SessionNextReasoningEnded,
    #[serde(rename = "session.next.reasoning.started")]
    SessionNextReasoningStarted,
    #[serde(rename = "session.next.retried")]
    SessionNextRetried,
    #[serde(rename = "session.next.revert.cleared")]
    SessionNextRevertCleared,
    #[serde(rename = "session.next.revert.committed")]
    SessionNextRevertCommitted,
    #[serde(rename = "session.next.revert.staged")]
    SessionNextRevertStaged,
    #[serde(rename = "session.next.shell.ended")]
    SessionNextShellEnded,
    #[serde(rename = "session.next.shell.started")]
    SessionNextShellStarted,
    #[serde(rename = "session.next.step.ended")]
    SessionNextStepEnded,
    #[serde(rename = "session.next.step.failed")]
    SessionNextStepFailed,
    #[serde(rename = "session.next.step.started")]
    SessionNextStepStarted,
    #[serde(rename = "session.next.synthetic")]
    SessionNextSynthetic,
    #[serde(rename = "session.next.text.delta")]
    SessionNextTextDelta,
    #[serde(rename = "session.next.text.ended")]
    SessionNextTextEnded,
    #[serde(rename = "session.next.text.started")]
    SessionNextTextStarted,
    #[serde(rename = "session.next.tool.called")]
    SessionNextToolCalled,
    #[serde(rename = "session.next.tool.failed")]
    SessionNextToolFailed,
    #[serde(rename = "session.next.tool.input.delta")]
    SessionNextToolInputDelta,
    #[serde(rename = "session.next.tool.input.ended")]
    SessionNextToolInputEnded,
    #[serde(rename = "session.next.tool.input.started")]
    SessionNextToolInputStarted,
    #[serde(rename = "session.next.tool.progress")]
    SessionNextToolProgress,
    #[serde(rename = "session.next.tool.success")]
    SessionNextToolSuccess,
    #[serde(rename = "session.status")]
    SessionStatus,
    #[serde(rename = "session.updated")]
    SessionUpdated,
    #[serde(rename = "todo.updated")]
    TodoUpdated,
    #[serde(rename = "tui.command.execute")]
    TuiCommandExecute,
    #[serde(rename = "tui.prompt.append")]
    TuiPromptAppend,
    #[serde(rename = "tui.session.select")]
    TuiSessionSelect,
    #[serde(rename = "tui.toast.show")]
    TuiToastShow,
    #[serde(rename = "vcs.branch.updated")]
    VcsBranchUpdated,
    #[serde(rename = "workspace.failed")]
    WorkspaceFailed,
    #[serde(rename = "workspace.ready")]
    WorkspaceReady,
    #[serde(rename = "workspace.status")]
    WorkspaceStatus,
    #[serde(rename = "worktree.failed")]
    WorktreeFailed,
    #[serde(rename = "worktree.ready")]
    WorktreeReady,
}

/// Number of public events defined by the contract (88).
pub const EVENT_TYPE_COUNT: usize = 88;

impl EventType {
    /// The wire representation (e.g. `session.next.step.ended`).
    pub const fn as_str(self) -> &'static str {
        match self {
            EventType::CatalogUpdated => "catalog.updated",
            EventType::CommandExecuted => "command.executed",
            EventType::FileEdited => "file.edited",
            EventType::FileWatcherUpdated => "file.watcher.updated",
            EventType::GlobalDisposed => "global.disposed",
            EventType::InstallationUpdateAvailable => "installation.update-available",
            EventType::InstallationUpdated => "installation.updated",
            EventType::IntegrationConnectionUpdated => "integration.connection.updated",
            EventType::IntegrationUpdated => "integration.updated",
            EventType::LspUpdated => "lsp.updated",
            EventType::McpBrowserOpenFailed => "mcp.browser.open.failed",
            EventType::McpToolsChanged => "mcp.tools.changed",
            EventType::MessagePartDelta => "message.part.delta",
            EventType::MessagePartRemoved => "message.part.removed",
            EventType::MessagePartUpdated => "message.part.updated",
            EventType::MessageRemoved => "message.removed",
            EventType::MessageUpdated => "message.updated",
            EventType::ModelsDevRefreshed => "models-dev.refreshed",
            EventType::PermissionAsked => "permission.asked",
            EventType::PermissionReplied => "permission.replied",
            EventType::PermissionV2Asked => "permission.v2.asked",
            EventType::PermissionV2Replied => "permission.v2.replied",
            EventType::PluginAdded => "plugin.added",
            EventType::ProjectDirectoriesUpdated => "project.directories.updated",
            EventType::ProjectUpdated => "project.updated",
            EventType::PtyCreated => "pty.created",
            EventType::PtyDeleted => "pty.deleted",
            EventType::PtyExited => "pty.exited",
            EventType::PtyUpdated => "pty.updated",
            EventType::QuestionAsked => "question.asked",
            EventType::QuestionRejected => "question.rejected",
            EventType::QuestionReplied => "question.replied",
            EventType::QuestionV2Asked => "question.v2.asked",
            EventType::QuestionV2Rejected => "question.v2.rejected",
            EventType::QuestionV2Replied => "question.v2.replied",
            EventType::ReferenceUpdated => "reference.updated",
            EventType::ServerConnected => "server.connected",
            EventType::SessionCompacted => "session.compacted",
            EventType::SessionCreated => "session.created",
            EventType::SessionDeleted => "session.deleted",
            EventType::SessionDiff => "session.diff",
            EventType::SessionError => "session.error",
            EventType::SessionIdle => "session.idle",
            EventType::SessionNextAgentSwitched => "session.next.agent.switched",
            EventType::SessionNextCompactionDelta => "session.next.compaction.delta",
            EventType::SessionNextCompactionEnded => "session.next.compaction.ended",
            EventType::SessionNextCompactionStarted => "session.next.compaction.started",
            EventType::SessionNextContextUpdated => "session.next.context.updated",
            EventType::SessionNextModelSwitched => "session.next.model.switched",
            EventType::SessionNextMoved => "session.next.moved",
            EventType::SessionNextPromptAdmitted => "session.next.prompt.admitted",
            EventType::SessionNextPrompted => "session.next.prompted",
            EventType::SessionNextReasoningDelta => "session.next.reasoning.delta",
            EventType::SessionNextReasoningEnded => "session.next.reasoning.ended",
            EventType::SessionNextReasoningStarted => "session.next.reasoning.started",
            EventType::SessionNextRetried => "session.next.retried",
            EventType::SessionNextRevertCleared => "session.next.revert.cleared",
            EventType::SessionNextRevertCommitted => "session.next.revert.committed",
            EventType::SessionNextRevertStaged => "session.next.revert.staged",
            EventType::SessionNextShellEnded => "session.next.shell.ended",
            EventType::SessionNextShellStarted => "session.next.shell.started",
            EventType::SessionNextStepEnded => "session.next.step.ended",
            EventType::SessionNextStepFailed => "session.next.step.failed",
            EventType::SessionNextStepStarted => "session.next.step.started",
            EventType::SessionNextSynthetic => "session.next.synthetic",
            EventType::SessionNextTextDelta => "session.next.text.delta",
            EventType::SessionNextTextEnded => "session.next.text.ended",
            EventType::SessionNextTextStarted => "session.next.text.started",
            EventType::SessionNextToolCalled => "session.next.tool.called",
            EventType::SessionNextToolFailed => "session.next.tool.failed",
            EventType::SessionNextToolInputDelta => "session.next.tool.input.delta",
            EventType::SessionNextToolInputEnded => "session.next.tool.input.ended",
            EventType::SessionNextToolInputStarted => "session.next.tool.input.started",
            EventType::SessionNextToolProgress => "session.next.tool.progress",
            EventType::SessionNextToolSuccess => "session.next.tool.success",
            EventType::SessionStatus => "session.status",
            EventType::SessionUpdated => "session.updated",
            EventType::TodoUpdated => "todo.updated",
            EventType::TuiCommandExecute => "tui.command.execute",
            EventType::TuiPromptAppend => "tui.prompt.append",
            EventType::TuiSessionSelect => "tui.session.select",
            EventType::TuiToastShow => "tui.toast.show",
            EventType::VcsBranchUpdated => "vcs.branch.updated",
            EventType::WorkspaceFailed => "workspace.failed",
            EventType::WorkspaceReady => "workspace.ready",
            EventType::WorkspaceStatus => "workspace.status",
            EventType::WorktreeFailed => "worktree.failed",
            EventType::WorktreeReady => "worktree.ready",
        }
    }

    /// Parse a wire event type.
    pub fn from_wire(s: &str) -> Option<Self> {
        match s {
            "catalog.updated" => Some(EventType::CatalogUpdated),
            "command.executed" => Some(EventType::CommandExecuted),
            "file.edited" => Some(EventType::FileEdited),
            "file.watcher.updated" => Some(EventType::FileWatcherUpdated),
            "global.disposed" => Some(EventType::GlobalDisposed),
            "installation.update-available" => Some(EventType::InstallationUpdateAvailable),
            "installation.updated" => Some(EventType::InstallationUpdated),
            "integration.connection.updated" => Some(EventType::IntegrationConnectionUpdated),
            "integration.updated" => Some(EventType::IntegrationUpdated),
            "lsp.updated" => Some(EventType::LspUpdated),
            "mcp.browser.open.failed" => Some(EventType::McpBrowserOpenFailed),
            "mcp.tools.changed" => Some(EventType::McpToolsChanged),
            "message.part.delta" => Some(EventType::MessagePartDelta),
            "message.part.removed" => Some(EventType::MessagePartRemoved),
            "message.part.updated" => Some(EventType::MessagePartUpdated),
            "message.removed" => Some(EventType::MessageRemoved),
            "message.updated" => Some(EventType::MessageUpdated),
            "models-dev.refreshed" => Some(EventType::ModelsDevRefreshed),
            "permission.asked" => Some(EventType::PermissionAsked),
            "permission.replied" => Some(EventType::PermissionReplied),
            "permission.v2.asked" => Some(EventType::PermissionV2Asked),
            "permission.v2.replied" => Some(EventType::PermissionV2Replied),
            "plugin.added" => Some(EventType::PluginAdded),
            "project.directories.updated" => Some(EventType::ProjectDirectoriesUpdated),
            "project.updated" => Some(EventType::ProjectUpdated),
            "pty.created" => Some(EventType::PtyCreated),
            "pty.deleted" => Some(EventType::PtyDeleted),
            "pty.exited" => Some(EventType::PtyExited),
            "pty.updated" => Some(EventType::PtyUpdated),
            "question.asked" => Some(EventType::QuestionAsked),
            "question.rejected" => Some(EventType::QuestionRejected),
            "question.replied" => Some(EventType::QuestionReplied),
            "question.v2.asked" => Some(EventType::QuestionV2Asked),
            "question.v2.rejected" => Some(EventType::QuestionV2Rejected),
            "question.v2.replied" => Some(EventType::QuestionV2Replied),
            "reference.updated" => Some(EventType::ReferenceUpdated),
            "server.connected" => Some(EventType::ServerConnected),
            "session.compacted" => Some(EventType::SessionCompacted),
            "session.created" => Some(EventType::SessionCreated),
            "session.deleted" => Some(EventType::SessionDeleted),
            "session.diff" => Some(EventType::SessionDiff),
            "session.error" => Some(EventType::SessionError),
            "session.idle" => Some(EventType::SessionIdle),
            "session.next.agent.switched" => Some(EventType::SessionNextAgentSwitched),
            "session.next.compaction.delta" => Some(EventType::SessionNextCompactionDelta),
            "session.next.compaction.ended" => Some(EventType::SessionNextCompactionEnded),
            "session.next.compaction.started" => Some(EventType::SessionNextCompactionStarted),
            "session.next.context.updated" => Some(EventType::SessionNextContextUpdated),
            "session.next.model.switched" => Some(EventType::SessionNextModelSwitched),
            "session.next.moved" => Some(EventType::SessionNextMoved),
            "session.next.prompt.admitted" => Some(EventType::SessionNextPromptAdmitted),
            "session.next.prompted" => Some(EventType::SessionNextPrompted),
            "session.next.reasoning.delta" => Some(EventType::SessionNextReasoningDelta),
            "session.next.reasoning.ended" => Some(EventType::SessionNextReasoningEnded),
            "session.next.reasoning.started" => Some(EventType::SessionNextReasoningStarted),
            "session.next.retried" => Some(EventType::SessionNextRetried),
            "session.next.revert.cleared" => Some(EventType::SessionNextRevertCleared),
            "session.next.revert.committed" => Some(EventType::SessionNextRevertCommitted),
            "session.next.revert.staged" => Some(EventType::SessionNextRevertStaged),
            "session.next.shell.ended" => Some(EventType::SessionNextShellEnded),
            "session.next.shell.started" => Some(EventType::SessionNextShellStarted),
            "session.next.step.ended" => Some(EventType::SessionNextStepEnded),
            "session.next.step.failed" => Some(EventType::SessionNextStepFailed),
            "session.next.step.started" => Some(EventType::SessionNextStepStarted),
            "session.next.synthetic" => Some(EventType::SessionNextSynthetic),
            "session.next.text.delta" => Some(EventType::SessionNextTextDelta),
            "session.next.text.ended" => Some(EventType::SessionNextTextEnded),
            "session.next.text.started" => Some(EventType::SessionNextTextStarted),
            "session.next.tool.called" => Some(EventType::SessionNextToolCalled),
            "session.next.tool.failed" => Some(EventType::SessionNextToolFailed),
            "session.next.tool.input.delta" => Some(EventType::SessionNextToolInputDelta),
            "session.next.tool.input.ended" => Some(EventType::SessionNextToolInputEnded),
            "session.next.tool.input.started" => Some(EventType::SessionNextToolInputStarted),
            "session.next.tool.progress" => Some(EventType::SessionNextToolProgress),
            "session.next.tool.success" => Some(EventType::SessionNextToolSuccess),
            "session.status" => Some(EventType::SessionStatus),
            "session.updated" => Some(EventType::SessionUpdated),
            "todo.updated" => Some(EventType::TodoUpdated),
            "tui.command.execute" => Some(EventType::TuiCommandExecute),
            "tui.prompt.append" => Some(EventType::TuiPromptAppend),
            "tui.session.select" => Some(EventType::TuiSessionSelect),
            "tui.toast.show" => Some(EventType::TuiToastShow),
            "vcs.branch.updated" => Some(EventType::VcsBranchUpdated),
            "workspace.failed" => Some(EventType::WorkspaceFailed),
            "workspace.ready" => Some(EventType::WorkspaceReady),
            "workspace.status" => Some(EventType::WorkspaceStatus),
            "worktree.failed" => Some(EventType::WorktreeFailed),
            "worktree.ready" => Some(EventType::WorktreeReady),
            _ => None,
        }
    }
}

impl std::fmt::Display for EventType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}
