#!/usr/bin/env python3
"""Generate crates/schema/src/event_type.rs from tests/fixtures/events.json.

The event name list is owned by the contract fixture; the Rust enum is derived so
the two can never drift. Run after scripts/extract_contract.py.
"""
from __future__ import annotations

import json
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
FIXTURE = REPO / "tests" / "fixtures" / "events.json"
OUT = REPO / "crates" / "schema" / "src" / "event_type.rs"


def pascal(name: str) -> str:
    parts = [p for p in re.split(r"[^0-9A-Za-z]+", name) if p]
    variant = "".join(p[:1].upper() + p[1:] for p in parts)
    if not variant or variant[0].isdigit():
        variant = "E" + variant
    return variant


def main() -> int:
    manifest = json.loads(FIXTURE.read_text())
    events = manifest["events"]

    seen: dict[str, str] = {}
    variants = []
    for event in events:
        base = pascal(event["type"])
        variant = base
        i = 2
        while variant in seen:
            variant = f"{base}{i}"
            i += 1
        seen[variant] = event["type"]
        variants.append((variant, event["type"]))

    lines = [
        "// @generated by scripts/gen_event_enum.py — do not edit by hand.",
        "// Source: tests/fixtures/events.json",
        "//",
        f"// Public event count: {manifest['event_count']}",
        "",
        "use serde::{Deserialize, Serialize};",
        "",
        "/// All public `V2Event` type discriminators.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]",
        "pub enum EventType {",
    ]
    for variant, wire in variants:
        lines.append(f'    #[serde(rename = "{wire}")]')
        lines.append(f"    {variant},")
    lines.append("}")
    lines.append("")
    lines.append(f"/// Number of public events defined by the contract ({manifest['event_count']}).")
    lines.append(f"pub const EVENT_TYPE_COUNT: usize = {len(variants)};")
    lines.append("")
    lines.append("impl EventType {")
    lines.append("    /// The wire representation (e.g. `session.next.step.ended`).")
    lines.append("    pub const fn as_str(self) -> &'static str {")
    lines.append("        match self {")
    for variant, wire in variants:
        lines.append(f'            EventType::{variant} => "{wire}",')
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    /// Parse a wire event type.")
    lines.append("    pub fn from_wire(s: &str) -> Option<Self> {")
    lines.append("        match s {")
    for variant, wire in variants:
        lines.append(f'            "{wire}" => Some(EventType::{variant}),')
    lines.append("            _ => None,")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("impl std::fmt::Display for EventType {")
    lines.append("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
    lines.append("        f.write_str(self.as_str())")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO)} with {len(variants)} variants")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
